python ucr.py --dataset AllGestureWiimoteY --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset UWaveGestureLibraryX --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DiatomSizeReduction --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FreezerSmallTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ScreenType --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MixedShapesSmallTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SonyAIBORobotSurface2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset LargeKitchenAppliances --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ProximalPhalanxOutlineCorrect --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset OSULeaf --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset OliveOil --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FreezerRegularTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Herring --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GesturePebbleZ1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MelbournePedestrian --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PhalangesOutlinesCorrect --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset CricketZ --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ACSF1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FaceFour --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SemgHandGenderCh2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Haptics --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset UWaveGestureLibraryY --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Coffee --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset TwoLeadECG --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DistalPhalanxOutlineAgeGroup --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MixedShapesRegularTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SmoothSubspace --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Meat --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ShapesAll --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset InsectEPGSmallTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset CinCECGTorso --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset BeetleFly --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Ham --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ProximalPhalanxTW --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ItalyPowerDemand --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GunPointMaleVersusFemale --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SonyAIBORobotSurface1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MedicalImages --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SmallKitchenAppliances --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PigCVP --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Crop --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Chinatown --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PLAID --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset RefrigerationDevices --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Wine --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Yoga --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset AllGestureWiimoteX --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DistalPhalanxTW --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Computers --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ElectricDevices --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Adiac --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset InlineSkate --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FacesUCR --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ShapeletSim --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GunPointAgeSpan --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Phoneme --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset CricketX --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Lightning2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Beef --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PowerCons --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Plane --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset NonInvasiveFetalECGThorax2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset UMD --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Wafer --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ToeSegmentation1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Car --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset UWaveGestureLibraryZ --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset EOGVerticalSignal --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset CBF --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset EOGHorizontalSignal --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Strawberry --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset StarLightCurves --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DodgerLoopGame --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FordA --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Fish --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PigArtPressure --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ShakeGestureWiimoteZ --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ECGFiveDays --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GunPointOldVersusYoung --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GesturePebbleZ2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ECG200 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Symbols --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FordB --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FaceAll --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MiddlePhalanxTW --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MiddlePhalanxOutlineCorrect --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GestureMidAirD1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset InsectEPGRegularTrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DodgerLoopDay --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ProximalPhalanxOutlineAgeGroup --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset HandOutlines --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SwedishLeaf --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset AllGestureWiimoteZ --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset InsectWingbeatSound --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MiddlePhalanxOutlineAgeGroup --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GestureMidAirD3 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ChlorineConcentration --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ArrowHead --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Fungi --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PigAirwayPressure --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset PickupGestureWiimoteZ --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Rock --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Worms --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Lightning7 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset BME --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SyntheticControl --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset MoteStrain --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SemgHandMovementCh2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Mallat --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GestureMidAirD2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset CricketY --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset NonInvasiveFetalECGThorax1 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ToeSegmentation2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset ECG5000 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Trace --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset WormsTwoClass --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset GunPoint --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset UWaveGestureLibraryAll --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset EthanolLevel --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset WordSynonyms --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset HouseTwenty --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DodgerLoopWeekend --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset Earthquakes --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset TwoPatterns --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset DistalPhalanxOutlineCorrect --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset SemgHandSubjectCh2 --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset FiftyWords --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python ucr.py --dataset BirdChicken --path /dev_data/zzj/hzy/datasets/UCR --hyper ./default_hyperparameters.json  --cuda --random_seed 42
