python -u train_ssl.py --dataset_name Herring --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ProximalPhalanxOutlineAgeGroup --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name UWaveGestureLibraryAll --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FiftyWords --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PLAID --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SmoothSubspace --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Lightning7 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Mallat --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FordB --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FaceFour --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Fungi --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name EOGHorizontalSignal --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ChlorineConcentration --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ECGFiveDays --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Computers --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name InsectEPGRegularTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DodgerLoopDay --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Wafer --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FaceAll --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MiddlePhalanxOutlineAgeGroup --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Phoneme --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SonyAIBORobotSurface2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DistalPhalanxOutlineAgeGroup --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GunPointOldVersusYoung --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name CBF --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Haptics --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name CinCECGTorso --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ECG5000 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MedicalImages --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ShakeGestureWiimoteZ --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Rock --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SmallKitchenAppliances --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name BeetleFly --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name WordSynonyms --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ItalyPowerDemand --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name LargeKitchenAppliances --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Yoga --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name HouseTwenty --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FordA --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Meat --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ToeSegmentation2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GestureMidAirD2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name NonInvasiveFetalECGThorax1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Adiac --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name UWaveGestureLibraryY --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Crop --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name BirdChicken --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name AllGestureWiimoteY --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ElectricDevices --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ShapeletSim --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name UWaveGestureLibraryX --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name CricketZ --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name OSULeaf --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DistalPhalanxOutlineCorrect --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FreezerRegularTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Ham --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name AllGestureWiimoteX --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MixedShapesRegularTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MiddlePhalanxOutlineCorrect --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Plane --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PigArtPressure --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SyntheticControl --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Fish --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MelbournePedestrian --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ShapesAll --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name InsectEPGSmallTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Symbols --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PhalangesOutlinesCorrect --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name AllGestureWiimoteZ --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name CricketY --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MixedShapesSmallTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name TwoLeadECG --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Chinatown --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ToeSegmentation1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name HandOutlines --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Worms --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SemgHandSubjectCh2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Wine --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ACSF1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ProximalPhalanxOutlineCorrect --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DodgerLoopWeekend --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DodgerLoopGame --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DistalPhalanxTW --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GesturePebbleZ2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PigAirwayPressure --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Beef --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Strawberry --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name BME --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MoteStrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name MiddlePhalanxTW --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FacesUCR --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GunPoint --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PickupGestureWiimoteZ --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GestureMidAirD1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ProximalPhalanxTW --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SwedishLeaf --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Lightning2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name OliveOil --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Coffee --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SemgHandGenderCh2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Car --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name InsectWingbeatSound --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GunPointMaleVersusFemale --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name RefrigerationDevices --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ArrowHead --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name InlineSkate --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name DiatomSizeReduction --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GunPointAgeSpan --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name FreezerSmallTrain --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name WormsTwoClass --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GesturePebbleZ1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name EthanolLevel --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ScreenType --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name TwoPatterns --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PowerCons --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name StarLightCurves --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Earthquakes --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name UWaveGestureLibraryZ --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SemgHandMovementCh2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name SonyAIBORobotSurface1 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name ECG200 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name GestureMidAirD3 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name PigCVP --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name EOGVerticalSignal --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name UMD --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name NonInvasiveFetalECGThorax2 --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name CricketX --model_name SelfTime --random_seed 42
python -u train_ssl.py --dataset_name Trace --model_name SelfTime --random_seed 42
