python src/main.py --dataset AllGestureWiimoteY --data_dir /dev_data/zzj/hzy/datasets/UCR/AllGestureWiimoteY --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset UWaveGestureLibraryX --data_dir /dev_data/zzj/hzy/datasets/UCR/UWaveGestureLibraryX --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DiatomSizeReduction --data_dir /dev_data/zzj/hzy/datasets/UCR/DiatomSizeReduction --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FreezerSmallTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/FreezerSmallTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ScreenType --data_dir /dev_data/zzj/hzy/datasets/UCR/ScreenType --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MixedShapesSmallTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/MixedShapesSmallTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SonyAIBORobotSurface2 --data_dir /dev_data/zzj/hzy/datasets/UCR/SonyAIBORobotSurface2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset LargeKitchenAppliances --data_dir /dev_data/zzj/hzy/datasets/UCR/LargeKitchenAppliances --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ProximalPhalanxOutlineCorrect --data_dir /dev_data/zzj/hzy/datasets/UCR/ProximalPhalanxOutlineCorrect --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset OSULeaf --data_dir /dev_data/zzj/hzy/datasets/UCR/OSULeaf --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset OliveOil --data_dir /dev_data/zzj/hzy/datasets/UCR/OliveOil --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FreezerRegularTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/FreezerRegularTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Herring --data_dir /dev_data/zzj/hzy/datasets/UCR/Herring --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GesturePebbleZ1 --data_dir /dev_data/zzj/hzy/datasets/UCR/GesturePebbleZ1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MelbournePedestrian --data_dir /dev_data/zzj/hzy/datasets/UCR/MelbournePedestrian --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PhalangesOutlinesCorrect --data_dir /dev_data/zzj/hzy/datasets/UCR/PhalangesOutlinesCorrect --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset CricketZ --data_dir /dev_data/zzj/hzy/datasets/UCR/CricketZ --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ACSF1 --data_dir /dev_data/zzj/hzy/datasets/UCR/ACSF1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FaceFour --data_dir /dev_data/zzj/hzy/datasets/UCR/FaceFour --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SemgHandGenderCh2 --data_dir /dev_data/zzj/hzy/datasets/UCR/SemgHandGenderCh2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Haptics --data_dir /dev_data/zzj/hzy/datasets/UCR/Haptics --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset UWaveGestureLibraryY --data_dir /dev_data/zzj/hzy/datasets/UCR/UWaveGestureLibraryY --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Coffee --data_dir /dev_data/zzj/hzy/datasets/UCR/Coffee --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset TwoLeadECG --data_dir /dev_data/zzj/hzy/datasets/UCR/TwoLeadECG --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DistalPhalanxOutlineAgeGroup --data_dir /dev_data/zzj/hzy/datasets/UCR/DistalPhalanxOutlineAgeGroup --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MixedShapesRegularTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/MixedShapesRegularTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SmoothSubspace --data_dir /dev_data/zzj/hzy/datasets/UCR/SmoothSubspace --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Meat --data_dir /dev_data/zzj/hzy/datasets/UCR/Meat --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ShapesAll --data_dir /dev_data/zzj/hzy/datasets/UCR/ShapesAll --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset InsectEPGSmallTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/InsectEPGSmallTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset CinCECGTorso --data_dir /dev_data/zzj/hzy/datasets/UCR/CinCECGTorso --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset BeetleFly --data_dir /dev_data/zzj/hzy/datasets/UCR/BeetleFly --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Ham --data_dir /dev_data/zzj/hzy/datasets/UCR/Ham --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ProximalPhalanxTW --data_dir /dev_data/zzj/hzy/datasets/UCR/ProximalPhalanxTW --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ItalyPowerDemand --data_dir /dev_data/zzj/hzy/datasets/UCR/ItalyPowerDemand --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GunPointMaleVersusFemale --data_dir /dev_data/zzj/hzy/datasets/UCR/GunPointMaleVersusFemale --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SonyAIBORobotSurface1 --data_dir /dev_data/zzj/hzy/datasets/UCR/SonyAIBORobotSurface1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MedicalImages --data_dir /dev_data/zzj/hzy/datasets/UCR/MedicalImages --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SmallKitchenAppliances --data_dir /dev_data/zzj/hzy/datasets/UCR/SmallKitchenAppliances --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PigCVP --data_dir /dev_data/zzj/hzy/datasets/UCR/PigCVP --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Crop --data_dir /dev_data/zzj/hzy/datasets/UCR/Crop --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Chinatown --data_dir /dev_data/zzj/hzy/datasets/UCR/Chinatown --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PLAID --data_dir /dev_data/zzj/hzy/datasets/UCR/PLAID --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset RefrigerationDevices --data_dir /dev_data/zzj/hzy/datasets/UCR/RefrigerationDevices --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Wine --data_dir /dev_data/zzj/hzy/datasets/UCR/Wine --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Yoga --data_dir /dev_data/zzj/hzy/datasets/UCR/Yoga --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset AllGestureWiimoteX --data_dir /dev_data/zzj/hzy/datasets/UCR/AllGestureWiimoteX --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DistalPhalanxTW --data_dir /dev_data/zzj/hzy/datasets/UCR/DistalPhalanxTW --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Computers --data_dir /dev_data/zzj/hzy/datasets/UCR/Computers --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ElectricDevices --data_dir /dev_data/zzj/hzy/datasets/UCR/ElectricDevices --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Adiac --data_dir /dev_data/zzj/hzy/datasets/UCR/Adiac --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset InlineSkate --data_dir /dev_data/zzj/hzy/datasets/UCR/InlineSkate --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FacesUCR --data_dir /dev_data/zzj/hzy/datasets/UCR/FacesUCR --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ShapeletSim --data_dir /dev_data/zzj/hzy/datasets/UCR/ShapeletSim --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GunPointAgeSpan --data_dir /dev_data/zzj/hzy/datasets/UCR/GunPointAgeSpan --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Phoneme --data_dir /dev_data/zzj/hzy/datasets/UCR/Phoneme --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset CricketX --data_dir /dev_data/zzj/hzy/datasets/UCR/CricketX --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Lightning2 --data_dir /dev_data/zzj/hzy/datasets/UCR/Lightning2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Beef --data_dir /dev_data/zzj/hzy/datasets/UCR/Beef --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PowerCons --data_dir /dev_data/zzj/hzy/datasets/UCR/PowerCons --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Plane --data_dir /dev_data/zzj/hzy/datasets/UCR/Plane --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset NonInvasiveFetalECGThorax2 --data_dir /dev_data/zzj/hzy/datasets/UCR/NonInvasiveFetalECGThorax2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset UMD --data_dir /dev_data/zzj/hzy/datasets/UCR/UMD --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Wafer --data_dir /dev_data/zzj/hzy/datasets/UCR/Wafer --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ToeSegmentation1 --data_dir /dev_data/zzj/hzy/datasets/UCR/ToeSegmentation1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Car --data_dir /dev_data/zzj/hzy/datasets/UCR/Car --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset UWaveGestureLibraryZ --data_dir /dev_data/zzj/hzy/datasets/UCR/UWaveGestureLibraryZ --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset EOGVerticalSignal --data_dir /dev_data/zzj/hzy/datasets/UCR/EOGVerticalSignal --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset CBF --data_dir /dev_data/zzj/hzy/datasets/UCR/CBF --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset EOGHorizontalSignal --data_dir /dev_data/zzj/hzy/datasets/UCR/EOGHorizontalSignal --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Strawberry --data_dir /dev_data/zzj/hzy/datasets/UCR/Strawberry --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset StarLightCurves --data_dir /dev_data/zzj/hzy/datasets/UCR/StarLightCurves --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DodgerLoopGame --data_dir /dev_data/zzj/hzy/datasets/UCR/DodgerLoopGame --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FordA --data_dir /dev_data/zzj/hzy/datasets/UCR/FordA --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Fish --data_dir /dev_data/zzj/hzy/datasets/UCR/Fish --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PigArtPressure --data_dir /dev_data/zzj/hzy/datasets/UCR/PigArtPressure --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ShakeGestureWiimoteZ --data_dir /dev_data/zzj/hzy/datasets/UCR/ShakeGestureWiimoteZ --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ECGFiveDays --data_dir /dev_data/zzj/hzy/datasets/UCR/ECGFiveDays --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GunPointOldVersusYoung --data_dir /dev_data/zzj/hzy/datasets/UCR/GunPointOldVersusYoung --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GesturePebbleZ2 --data_dir /dev_data/zzj/hzy/datasets/UCR/GesturePebbleZ2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ECG200 --data_dir /dev_data/zzj/hzy/datasets/UCR/ECG200 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Symbols --data_dir /dev_data/zzj/hzy/datasets/UCR/Symbols --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FordB --data_dir /dev_data/zzj/hzy/datasets/UCR/FordB --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FaceAll --data_dir /dev_data/zzj/hzy/datasets/UCR/FaceAll --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MiddlePhalanxTW --data_dir /dev_data/zzj/hzy/datasets/UCR/MiddlePhalanxTW --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MiddlePhalanxOutlineCorrect --data_dir /dev_data/zzj/hzy/datasets/UCR/MiddlePhalanxOutlineCorrect --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GestureMidAirD1 --data_dir /dev_data/zzj/hzy/datasets/UCR/GestureMidAirD1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset InsectEPGRegularTrain --data_dir /dev_data/zzj/hzy/datasets/UCR/InsectEPGRegularTrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DodgerLoopDay --data_dir /dev_data/zzj/hzy/datasets/UCR/DodgerLoopDay --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ProximalPhalanxOutlineAgeGroup --data_dir /dev_data/zzj/hzy/datasets/UCR/ProximalPhalanxOutlineAgeGroup --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset HandOutlines --data_dir /dev_data/zzj/hzy/datasets/UCR/HandOutlines --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SwedishLeaf --data_dir /dev_data/zzj/hzy/datasets/UCR/SwedishLeaf --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset AllGestureWiimoteZ --data_dir /dev_data/zzj/hzy/datasets/UCR/AllGestureWiimoteZ --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset InsectWingbeatSound --data_dir /dev_data/zzj/hzy/datasets/UCR/InsectWingbeatSound --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MiddlePhalanxOutlineAgeGroup --data_dir /dev_data/zzj/hzy/datasets/UCR/MiddlePhalanxOutlineAgeGroup --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GestureMidAirD3 --data_dir /dev_data/zzj/hzy/datasets/UCR/GestureMidAirD3 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ChlorineConcentration --data_dir /dev_data/zzj/hzy/datasets/UCR/ChlorineConcentration --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ArrowHead --data_dir /dev_data/zzj/hzy/datasets/UCR/ArrowHead --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Fungi --data_dir /dev_data/zzj/hzy/datasets/UCR/Fungi --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PigAirwayPressure --data_dir /dev_data/zzj/hzy/datasets/UCR/PigAirwayPressure --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset PickupGestureWiimoteZ --data_dir /dev_data/zzj/hzy/datasets/UCR/PickupGestureWiimoteZ --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Rock --data_dir /dev_data/zzj/hzy/datasets/UCR/Rock --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Worms --data_dir /dev_data/zzj/hzy/datasets/UCR/Worms --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Lightning7 --data_dir /dev_data/zzj/hzy/datasets/UCR/Lightning7 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset BME --data_dir /dev_data/zzj/hzy/datasets/UCR/BME --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SyntheticControl --data_dir /dev_data/zzj/hzy/datasets/UCR/SyntheticControl --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset MoteStrain --data_dir /dev_data/zzj/hzy/datasets/UCR/MoteStrain --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SemgHandMovementCh2 --data_dir /dev_data/zzj/hzy/datasets/UCR/SemgHandMovementCh2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Mallat --data_dir /dev_data/zzj/hzy/datasets/UCR/Mallat --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GestureMidAirD2 --data_dir /dev_data/zzj/hzy/datasets/UCR/GestureMidAirD2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset CricketY --data_dir /dev_data/zzj/hzy/datasets/UCR/CricketY --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset NonInvasiveFetalECGThorax1 --data_dir /dev_data/zzj/hzy/datasets/UCR/NonInvasiveFetalECGThorax1 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ToeSegmentation2 --data_dir /dev_data/zzj/hzy/datasets/UCR/ToeSegmentation2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset ECG5000 --data_dir /dev_data/zzj/hzy/datasets/UCR/ECG5000 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Trace --data_dir /dev_data/zzj/hzy/datasets/UCR/Trace --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset WormsTwoClass --data_dir /dev_data/zzj/hzy/datasets/UCR/WormsTwoClass --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset GunPoint --data_dir /dev_data/zzj/hzy/datasets/UCR/GunPoint --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset UWaveGestureLibraryAll --data_dir /dev_data/zzj/hzy/datasets/UCR/UWaveGestureLibraryAll --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset EthanolLevel --data_dir /dev_data/zzj/hzy/datasets/UCR/EthanolLevel --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset WordSynonyms --data_dir /dev_data/zzj/hzy/datasets/UCR/WordSynonyms --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset HouseTwenty --data_dir /dev_data/zzj/hzy/datasets/UCR/HouseTwenty --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DodgerLoopWeekend --data_dir /dev_data/zzj/hzy/datasets/UCR/DodgerLoopWeekend --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset Earthquakes --data_dir /dev_data/zzj/hzy/datasets/UCR/Earthquakes --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset TwoPatterns --data_dir /dev_data/zzj/hzy/datasets/UCR/TwoPatterns --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset DistalPhalanxOutlineCorrect --data_dir /dev_data/zzj/hzy/datasets/UCR/DistalPhalanxOutlineCorrect --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset SemgHandSubjectCh2 --data_dir /dev_data/zzj/hzy/datasets/UCR/SemgHandSubjectCh2 --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset FiftyWords --data_dir /dev_data/zzj/hzy/datasets/UCR/FiftyWords --batch_size 128 --task classification  --gpu 0 --epochs 1000
python src/main.py --dataset BirdChicken --data_dir /dev_data/zzj/hzy/datasets/UCR/BirdChicken --batch_size 128 --task classification  --gpu 0 --epochs 1000
