python uea.py --dataset CharacterTrajectories --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset PenDigits --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset InsectWingbeat --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset ArticularyWordRecognition --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset Heartbeat --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset Handwriting --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset AtrialFibrillation --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset PhonemeSpectra --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset BasicMotions --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset SelfRegulationSCP1 --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset JapaneseVowels --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset UWaveGestureLibrary --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset Libras --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset EthanolConcentration --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset RacketSports --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset NATOPS --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset StandWalkJump --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset ERing --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset HandMovementDirection --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset SelfRegulationSCP2 --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset Epilepsy --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset FaceDetection --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset PEMS-SF --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset Cricket --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset SpokenArabicDigits --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset DuckDuckGeese --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset FingerMovements --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset EigenWorms --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset MotorImagery --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
python uea.py --dataset LSST --path /dev_data/zzj/hzy/datasets/UEA --hyper ./default_hyperparameters.json  --cuda --random_seed 42
